version: "3.8"

services:
  mysqldb:
    image: "mysql:${MYSQLDB_VERSION}"
    container_name: "${MYSQLDB_SERVER_NAME}"
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQLDB_DB_NAME}"
        MYSQL_USER: "${MYSQLDB_USER}"
        MYSQL_PASSWORD: "${MYSQLDB_USER_PASSWORD}"
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  insurance_agency:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    restart: on-failure
    ports:
      - "${SPRING_DOCKER_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      DB_SERVER: "${MYSQLDB_SERVER_NAME}"
      DB_PORT: "${MYSQLDB_DOCKER_PORT}"
      USER: "${MYSQLDB_USER}"
      PASSWORD: "${MYSQLDB_USER_PASSWORD}"
      APP_PORT: "${SPRING_DOCKER_PORT}"
      DB_NAME: "${MYSQLDB_DB_NAME}"
