INSERT INTO offer(title, period_in_months, description, price, is_active, company_id, insurance_type_id)
VALUES
('Basic Auto Insurance', 12, 'Coverage for damages caused by accidents', 100.00, 1, 1, 1),
('Comprehensive Auto Insurance', 24, 'Coverage for damages caused by accidents, theft, and natural disasters', 200.00, 1, 2, 1),
('Collision Auto Insurance', 6, 'Coverage for damages caused by collisions with other vehicles or objects', 75.00, 1, 3, 1),
('Liability Auto Insurance', 12, 'Coverage for damages or injuries caused by the policyholder to third parties', 120.00, 1, 4, 1),
('Personal Injury Protection', 6, 'Coverage for medical expenses and lost wages for the policyholder and passengers in case of an accident', 50.00, 1, 5, 1),
('Uninsured Motorist Insurance', 12, 'Coverage for damages caused by uninsured or hit-and-run drivers', 80.00, 1, 6, 1),
('Roadside Assistance', 12, 'Coverage for towing and emergency roadside services', 60.00, 1, 7, 1),
('Rental Reimbursement', 6, 'Coverage for rental car expenses while the policyholder\'s car is being repaired', 90.00, 1, 8, 1),
('Gap Insurance', 24, 'Coverage for the difference between the actual cash value and the amount owed on a car in case of a total loss', 150.00, 1, 9, 1),
('Classic Car Insurance', 12, 'Coverage for antique, classic, or vintage cars', 300.00, 1, 10, 1),
('Basic Auto Insurance', 12, 'Coverage for damages caused by accidents', 100.00, 1, 1, 1),
('Comprehensive Auto Insurance', 24, 'Coverage for damages caused by accidents, theft, and natural disasters', 200.00, 1, 2, 1),
('Collision Auto Insurance', 6, 'Coverage for damages caused by collisions with other vehicles or objects', 75.00, 1, 3, 1),
('Liability Auto Insurance', 12, 'Coverage for damages or injuries caused by the policyholder to third parties', 120.00, 1, 4, 1),
("Basic Liability Insurance", 12, "Covers bodily injury and property damage that you cause to another person in an accident", 150.00, 1, 1, 1),
("Comprehensive Coverage", 12, "Covers damage to your car caused by something other than a collision, like theft, vandalism, or natural disasters", 250.00, 1, 2, 1),
("Collision Coverage", 12, "Covers damage to your car caused by a collision with another car or object", 200.00, 1, 3, 1),
("Personal Injury Protection", 12, "Covers medical expenses and lost wages for you and your passengers if you're injured in an accident, regardless of who caused it", 175.00, 1, 4, 1),
("Uninsured/Underinsured Motorist Coverage", 12, "Covers you if you're hit by a driver who doesn't have enough insurance, or doesn't have insurance at all", 225.00, 1, 5, 1),
("Rental Car Coverage", 12, "Covers the cost of a rental car if your car is being repaired after an accident", 175.00, 1, 6, 1),
("Roadside Assistance Coverage", 12, "Covers emergency roadside services like towing, battery jump-starts, and flat tire changes", 100.00, 1, 7, 1),
("Accident Forgiveness", 12, "Prevents your rates from going up after your first accident", 125.00, 1, 8, 1),
("New Car Replacement", 12, "Replaces your car with a new one of the same make and model if it's totaled in the first year of ownership", 300.00, 1, 9, 1),
("Gap Insurance", 12, "Covers the difference between what you owe on your car loan and what your car is worth if it's totaled or stolen", 175.00, 1, 10, 1),
("Home Insurance Basic", 12, "Covers damage to your home from fire, lightning, and hail.", 50.00, 1, 1, 2),
("Home Insurance Premium", 24, "Provides comprehensive protection for your home and belongings.", 100.00, 1, 2, 2),
("Home Insurance Plus", 6, "Covers accidental damage to your home and personal belongings.", 75.00, 1, 3, 2),
("Family Home Insurance", 12, "Covers damage to your home and personal belongings, as well as liability protection.", 90.00, 1, 4, 2),
("Homeowners Insurance Bundle", 12, "Provides a bundled package of home and auto insurance.", 150.00, 1, 5, 2),
("Condo Insurance", 6, "Covers damage to your condominium unit and personal property.", 60.00, 1, 6, 2),
("Rental Property Insurance", 12, "Provides protection for landlords against damage caused by tenants.", 85.00, 1, 7, 2),
("Vacation Home Insurance", 6, "Covers your second home or vacation property from damage and theft.", 95.00, 1, 8, 2),
("High-Value Home Insurance", 24, "Provides coverage for high-value homes and personal belongings.", 250.00, 1, 9, 2),
("Mortgage Insurance", 12, "Protects homeowners from defaulting on their mortgage payments.", 30.00, 1, 10, 2),
("Home Insurance Basic", 12, "Covers damage to your home from fire, lightning, and hail.", 50.00, 1, 1, 2),
("Home Insurance Premium", 24, "Provides comprehensive protection for your home and belongings.", 100.00, 1, 2, 2),
("Home Insurance Plus", 6, "Covers accidental damage to your home and personal belongings.", 75.00, 1, 3, 2),
("Family Home Insurance", 12, "Covers damage to your home and personal belongings, as well as liability protection.", 90.00, 1, 4, 2),
("Homeowners Insurance Bundle", 12, "Provides a bundled package of home and auto insurance.", 150.00, 1, 5, 2),
("Condo Insurance", 6, "Covers damage to your condominium unit and personal property.", 60.00, 1, 6, 2),
("Rental Property Insurance", 12, "Provides protection for landlords against damage caused by tenants.", 85.00, 1, 7, 2),
("Vacation Home Insurance", 6, "Covers your second home or vacation property from damage and theft.", 95.00, 1, 8, 2),
("High-Value Home Insurance", 24, "Provides coverage for high-value homes and personal belongings.", 250.00, 1, 9, 2),
("Mortgage Insurance", 12, "Protects homeowners from defaulting on their mortgage payments.", 30.00, 1, 10, 2),
('Basic renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, and vandalism', 100.00, 1, 1, 3),
('Comprehensive renters insurance', 6, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, and natural disasters', 150.00, 1, 2, 3),
('Premium renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, and natural disasters, as well as additional living expenses', 200.00, 1, 3, 3),
('Affordable renters insurance', 3, 'Covers damages to the rental property and personal belongings caused by fire, theft, and vandalism', 75.00, 1, 4, 3),
('Flexible renters insurance', 6, 'Allows you to customize your coverage to meet your specific needs and budget', 125.00, 1, 5, 3),
('Deluxe renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, natural disasters, as well as additional living expenses and personal liability', 250.00, 1, 6, 3),
('Standard renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, and vandalism, as well as personal liability', 125.00, 1, 7, 3),
('Ultimate renters insurance', 6, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, natural disasters, as well as additional living expenses and personal liability, and includes identity theft protection', 300.00, 1, 8, 3),
('Value renters insurance', 3, 'Covers damages to the rental property and personal belongings caused by fire, theft, and vandalism, and offers a lower cost option for those on a budget', 50.00, 1, 9, 3),
('Exclusive renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, natural disasters, as well as additional living expenses and personal liability, and includes high-value item coverage', 350.00, 1, 10, 3),
('Budget renters insurance', 6, 'Covers damages to the rental property and personal belongings caused by fire, theft, and vandalism, and offers a lower cost option for those on a budget', 75.00, 1, 1, 3),
('Premium Plus renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, natural disasters, as well as additional living expenses and personal liability, and includes high-value item coverage and identity theft protection', 400.00, 1, 2, 3),
('Full Protection renters insurance', 12, 'Covers damages to the rental property and personal belongings caused by fire, theft, vandalism, natural disasters, as well as additional living expenses and personal liability, and includes high-value item coverage, identity theft protection, and legal expenses', 500.00, 1, 3, 3),
('Life Insurance Basic', 12, 'A basic life insurance policy covering death by accident or illness.', 50.00, 1, 1, 4),
('Life Insurance Standard', 24, 'A standard life insurance policy covering death by accident or illness.', 100.00, 1, 2, 4),
('Life Insurance Premium', 36, 'A premium life insurance policy covering death by accident or illness.', 150.00, 1, 3, 4),
('Senior Life Insurance Basic', 12, 'A basic life insurance policy designed for senior citizens covering death by accident or illness.', 75.00, 1, 4, 4),
('Senior Life Insurance Standard', 24, 'A standard life insurance policy designed for senior citizens covering death by accident or illness.', 125.00, 1, 5, 4),
('Senior Life Insurance Premium', 36, 'A premium life insurance policy designed for senior citizens covering death by accident or illness.', 200.00, 1, 6, 4),
('Family Life Insurance Basic', 12, 'A basic life insurance policy designed for families covering death by accident or illness.', 100.00, 1, 7, 4),
('Family Life Insurance Standard', 24, 'A standard life insurance policy designed for families covering death by accident or illness.', 175.00, 1, 8, 4),
('Family Life Insurance Premium', 36, 'A premium life insurance policy designed for families covering death by accident or illness.', 250.00, 1, 9, 4),
('Mortgage Protection Insurance', 12, 'A life insurance policy designed to pay off the remaining mortgage balance in case of death.', 75.00, 1, 10, 4),
('Term Life Insurance Basic', 12, 'A basic term life insurance policy covering death by accident or illness.', 25.00, 1, 1, 4),
('Term Life Insurance Standard', 24, 'A standard term life insurance policy covering death by accident or illness.', 50.00, 1, 2, 4),
('Term Life Insurance Premium', 36, 'A premium term life insurance policy covering death by accident or illness.', 75.00, 1, 3, 4),
('Senior Term Life Insurance Basic', 12, 'A basic term life insurance policy designed for senior citizens covering death by accident or illness.', 50.00, 1, 4, 4),
('Senior Term Life Insurance Standard', 24, 'A standard term life insurance policy designed for senior citizens covering death by accident or illness.', 100.00, 1, 5, 4),
('Senior Term Life Insurance Premium', 36, 'A premium term life insurance policy designed for senior citizens covering death by accident or illness.', 150.00, 1, 6, 4),
('Family Term Life Insurance Basic', 12, 'A basic term life insurance policy designed for families covering death by accident or illness.', 75.00, 1, 7, 4),
('Family Term Life Insurance Standard', 24, 'A standard term life insurance policy designed for families covering death by accident or illness.', 125.00, 1, 8, 4),
('Family Term Life Insurance Premium', 36, 'A premium term life insurance policy designed for families covering death by accident or illness.', 175.00, 1, 9, 4),
('Basic Health Insurance', 12, 'Covers basic medical expenses', 100.00, 1, 1, 5),
('Comprehensive Health Insurance', 24, 'Covers hospitalization and surgery expenses', 200.00, 1, 2, 5),
('Family Health Insurance', 36, 'Covers medical expenses for the whole family', 300.00, 1, 3, 5),
('Dental Insurance', 6, 'Covers dental expenses', 50.00, 1, 4, 5),
('Vision Insurance', 12, 'Covers vision expenses', 75.00, 1, 5, 5),
('Senior Citizen Health Insurance', 36, 'Covers medical expenses for senior citizens', 250.00, 1, 6, 5),
('Maternity Insurance', 9, 'Covers pregnancy expenses', 150.00, 1, 7, 5),
('Child Health Insurance', 24, 'Covers medical expenses for children', 175.00, 1, 8, 5),
('Mental Health Insurance', 12, 'Covers mental health expenses', 125.00, 1, 9, 5),
('Accidental Health Insurance', 6, 'Covers medical expenses due to accidents', 75.00, 1, 10, 5),
('Health Insurance Plan A', 12, 'Covers doctor visits, hospital stays, and prescription drugs', 3000.00, 1, 1, 5),
('Health Insurance Plan B', 6, 'Covers emergency services, lab tests, and some prescription drugs', 1500.00, 1, 2, 5),
('Health Insurance Plan C', 24, 'Covers preventive care, mental health, and specialist visits', 5000.00, 1, 3, 5),
('Health Insurance Plan D', 12, 'Covers hospitalization, surgery, and medical equipment', 4500.00, 1, 4, 5),
('Health Insurance Plan E', 18, 'Covers routine check-ups, diagnostic tests, and therapy', 4000.00, 1, 5, 5),
('Health Insurance Plan F', 12, 'Covers prescription drugs, emergency care, and maternity services', 3500.00, 1, 6, 5),
('Health Insurance Plan G', 6, 'Covers physical therapy, chiropractic care, and acupuncture', 2000.00, 1, 7, 5),
('Health Insurance Plan H', 24, 'Covers inpatient care, outpatient care, and medical supplies', 5500.00, 1, 8, 5),
('Health Insurance Plan I', 18, 'Covers cancer treatment, organ transplants, and clinical trials', 7000.00, 1, 9, 5),
('Health Insurance Plan J', 12, 'Covers dental care, vision care, and hearing aids', 2500.00, 1, 10, 5),
('Basic travel insurance', 12, 'Covers basic medical expenses, trip cancellation, and trip interruption', 50.00, 1, 1, 6),
('Comprehensive travel insurance', 24, 'Covers all aspects of travel including medical expenses, trip cancellation, and lost or delayed baggage', 100.00, 1, 2, 6),
('International travel insurance', 12, 'Covers medical expenses, emergency medical evacuation, and repatriation', 75.00, 1, 3, 6),
('Domestic travel insurance', 6, 'Covers trip cancellation and lost or stolen baggage', 25.00, 1, 4, 6),
('Extended travel insurance', 36, 'Covers all aspects of travel including medical expenses, trip cancellation, and lost or delayed baggage', 150.00, 1, 5, 6),
('Group travel insurance', 12, 'Covers medical expenses and trip cancellation for groups of 10 or more', 40.00, 1, 6, 6),
('Single trip travel insurance', 1, 'Covers medical expenses and trip cancellation for a single trip', 10.00, 1, 7, 6),
('Multi-trip travel insurance', 12, 'Covers medical expenses and trip cancellation for multiple trips in a year', 75.00, 1, 8, 6),
('Cruise travel insurance', 6, 'Covers medical expenses and trip cancellation for cruises', 50.00, 1, 9, 6),
('Adventure travel insurance', 12, 'Covers medical expenses and trip cancellation for adventure travel such as hiking and skiing', 100.00, 1, 10, 6),
('Europe Travel Insurance', 6, 'Travel insurance for traveling in Europe', 120.00, 1, 2, 6),
('Asia Travel Insurance', 12, 'Travel insurance for traveling in Asia', 150.00, 1, 3, 6),
('South America Travel Insurance', 6, 'Travel insurance for traveling in South America', 90.00, 1, 4, 6),
('Australia Travel Insurance', 12, 'Travel insurance for traveling in Australia', 200.00, 1, 5, 6),
('Africa Travel Insurance', 6, 'Travel insurance for traveling in Africa', 100.00, 1, 6, 6),
('North America Travel Insurance', 12, 'Travel insurance for traveling in North America', 180.00, 1, 7, 6),
('Antarctica Travel Insurance', 3, 'Travel insurance for traveling in Antarctica', 250.00, 1, 8, 6),
('Caribbean Travel Insurance', 6, 'Travel insurance for traveling in Caribbean', 120.00, 1, 9, 6),
('Middle East Travel Insurance', 12, 'Travel insurance for traveling in Middle East', 150.00, 1, 10, 6),
('Worldwide Travel Insurance', 12, 'Travel insurance for worldwide travel', 250.00, 1, 1, 6);